spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.222.100:3306/guli_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  application:
    name: gulimall-oms
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.10:8848


mybatis-plus:
  mapper-locations: classpath:/mapper/pms/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 12000
