server:
  port: 88
spring:
  cloud:
    gateway:
      routes:
      - id: pms_route
        uri: lb://gulimall-pms
        predicates:
          - Path=/pms/**
      - id: oms_route
        uri: lb://gulimall-oms
        predicates:
          - Path=/oms/**
      - id: sms_route
          uri: lb://gulimall-sms
          predicates:
            - Path=/sms/**
      - id: ums_route
          uri: lb://gulimall-ums
          predicates:
            - Path=/ums/**
      - id: wms_route
          uri: lb://gulimall-wms
          predicates:
            - Path=/wms/**
#      跨域配置
#      globalcors:
#        cors-configurations:
#          '[/**]':
#              allowedOrigins: *
#              allowedMethods: *
#              allowCredentialls: ture
